#pragma once

#include <WinSock2.h>
#include <cstdio>
#include <vector>
#include <functional>
#include <memory>
#include <algorithm>
#include <deque>
#include <unordered_map>
#include <random>
#include <unordered_set>
#include <thread>
#include <mutex>
#include <shared_mutex>
#include <iterator>
#include <chrono>
#include <queue>
#include <utility>
#include <string>
#include <sqlext.h>
